/** Zonas habituales (IANA). El usuario puede escribir otra en el desplegable si el navegador la lista. */
export const TIMEZONE_PRESETS: { value: string; label: string }[] = [
  { value: "Europe/Madrid", label: "España — Madrid" },
  { value: "Atlantic/Canary", label: "España — Canarias" },
  { value: "Europe/London", label: "Reino Unido — Londres" },
  { value: "Europe/Paris", label: "Francia — París" },
  { value: "Europe/Berlin", label: "Alemania — Berlín" },
  { value: "Europe/Rome", label: "Italia — Roma" },
  { value: "America/Mexico_City", label: "México" },
  { value: "America/Bogota", label: "Colombia — Bogotá" },
  { value: "America/Lima", label: "Perú — Lima" },
  { value: "America/Santiago", label: "Chile — Santiago" },
  { value: "America/Buenos_Aires", label: "Argentina — Buenos Aires" },
  { value: "America/Sao_Paulo", label: "Brasil — São Paulo" },
  { value: "America/New_York", label: "EE. UU. — Este" },
  { value: "America/Chicago", label: "EE. UU. — Centro" },
  { value: "America/Denver", label: "EE. UU. — Montaña" },
  { value: "America/Los_Angeles", label: "EE. UU. — Pacífico" },
  { value: "America/Toronto", label: "Canadá — Toronto" },
  { value: "UTC", label: "UTC (referencia)" },
  { value: "Africa/Casablanca", label: "Marruecos" },
  { value: "Asia/Tokyo", label: "Japón — Tokio" },
  { value: "Asia/Dubai", label: "Emiratos — Dubái" },
  { value: "Australia/Sydney", label: "Australia — Sídney" },
];
